title: "David J. Castillo-Cornejo, Ph.D."
url: "https://muspelheimerscience.github.io"
baseurl: "/online-cv"
cv_pdf: "David_Castillo_CV.pdf"
description: "Ph.D. Scientist and Technologist"
theme_skin: ceramic

sass:
  sass_dir: _sass
  style: compressed

encoding: "utf-8"
